# -*- coding: utf-8 -*-
"""experiments.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G8Hcl7cpS9RCfp5Uoz3aYcsY_tB87I4b
"""



# Install dependencies (only needed if not already available in Colab)
!pip install tensorflow keras

# Import libraries
import numpy as np
import tensorflow as tf
from tensorflow.keras import datasets, layers, models
from tensorflow.keras.utils import to_categorical
import matplotlib.pyplot as plt

# Load the MNIST dataset
(train_images, train_labels_raw), (test_images, test_labels_raw) = datasets.mnist.load_data()

# Normalize pixel values to be between 0 and 1
train_images = train_images / 255.0
test_images = test_images / 255.0

# Reshape images to (28, 28, 1) for grayscale input
train_images = train_images.reshape((train_images.shape[0], 28, 28, 1))
test_images = test_images.reshape((test_images.shape[0], 28, 28, 1))

# Convert labels to one-hot encoding
train_labels = to_categorical(train_labels_raw, 10)
test_labels = to_categorical(test_labels_raw, 10)

# Build the CNN model
model = models.Sequential()

# First Convolutional Layer
model.add(layers.Conv2D(32, (3,3), activation='relu', input_shape=(28,28,1)))
model.add(layers.MaxPooling2D((2,2)))

# Second Convolutional Layer
model.add(layers.Conv2D(64, (3,3), activation='relu'))
model.add(layers.MaxPooling2D((2,2)))

# Third Convolutional Layer
model.add(layers.Conv2D(64, (3,3), activation='relu'))

# Flatten and Dense layers
model.add(layers.Flatten())
model.add(layers.Dense(64, activation='relu'))

# Output layer with 10 neurons (digits 0–9)
model.add(layers.Dense(10, activation='softmax'))

# Compile the model
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# Train the model
model.fit(train_images, train_labels, epochs=5, batch_size=64,
          validation_data=(test_images, test_labels))

# Evaluate the model
test_loss, test_acc = model.evaluate(test_images, test_labels)
print(f"Test accuracy: {test_acc * 100:.2f}%")

# Make predictions
predictions = model.predict(test_images)

# Example: show prediction for a specific test image
index = 10   # change this index to see other digits
plt.imshow(test_images[index].reshape(28,28), cmap='gray')
plt.title(f"True Label: {test_labels_raw[index]}, Predicted: {np.argmax(predictions[index])}")
plt.show()